import React from 'react';

function MuscleMap() {

	return (
    <div className="muscle-map">
      <img
        src="exercise-images/site-images/MuscleDiagram.png"
        className="body-diagram-image"
        alt="muscle-diagram"
      />
      <img
        src="exercise-images/site-images/muscle-map/01.A-Quads.png"
        className="muscle-image-quadA"
        alt="QuadA"
      />
      <img
        src="exercise-images/site-images/muscle-map/01.B-Quads.png"
        className="muscle-image-quadB"
        alt="QuadB"
      />
      <img
        src="exercise-images/site-images/muscle-map/04.-Obliques.png"
        className="muscle-image-abs"
        alt="Abs"
      />
      <img
        src="exercise-images/site-images/muscle-map/05.A-Biceps.png"
        className="muscle-image-bicepsA"
        alt="BicepsA"
      />
      <img
        src="exercise-images/site-images/muscle-map/05.B-Biceps.png"
        className="muscle-image-bicepsB"
        alt="BicepsB"
      />
      <img
        src="exercise-images/site-images/muscle-map/06.-Pecs.png"
        className="muscle-image-pecs"
        alt="Pecs"
      />
      <img
        src="exercise-images/site-images/muscle-map/07.A-Deltoids.png"
        className="muscle-image-deltoidA"
        alt="DeltoidA"
      />
      <img
        src="exercise-images/site-images/muscle-map/07.B-Deltoids.png"
        className="muscle-image-deltoidB"
        alt="DeltoidB"
      />
      <img
        src="exercise-images/site-images/muscle-map/13.A-Calves.png"
        className="muscle-image-calvesA"
        alt="CalvesA"
      />
      <img
        src="exercise-images/site-images/muscle-map/13.B-Calves.png"
        className="muscle-image-calvesB"
        alt="CalvesB"
      />
      {/* Back side */}
      <img
        src="exercise-images/site-images/muscle-map/07.C-Deltoids.png"
        className="muscle-image-deltoidC"
        alt="DeltoidC"
      />
      <img
        src="exercise-images/site-images/muscle-map/07.D-Deltoids.png"
        className="muscle-image-deltoidD"
        alt="DeltoidD"
      />
      <img
        src="exercise-images/site-images/muscle-map/08.C-Traps.png"
        className="muscle-image-trapsC"
        alt="TrapsC"
      />
      <img
        src="exercise-images/site-images/muscle-map/10.A-Lats.png"
        className="muscle-image-latsA"
        alt="LatsA"
      />
      <img
        src="exercise-images/site-images/muscle-map/10.B-Lats.png"
        className="muscle-image-latsB"
        alt="LatsB"
      />
      <img
        src="exercise-images/site-images/muscle-map/15.-Lower-back.png"
        className="muscle-image-lower-back"
        alt="Lower-back"
      />
      <img
        src="exercise-images/site-images/muscle-map/09.A-Triceps.png"
        className="muscle-image-tricepsA"
        alt="TricepsA"
      />
      <img
        src="exercise-images/site-images/muscle-map/09.B-Triceps.png"
        className="muscle-image-tricepsB"
        alt="TricepsB"
      />
      <img
        src="exercise-images/site-images/muscle-map/11.-Glutes.png"
        className="muscle-image-glutes"
        alt="Glutes"
      />
      <img
        src="exercise-images/site-images/muscle-map/12.A-Hamstrings.png"
        className="muscle-image-hamstringsA"
        alt="HamstringsA"
      />
      <img
        src="exercise-images/site-images/muscle-map/12.B-Hamstrings.png"
        className="muscle-image-hamstringsB"
        alt="HamstringsB"
      />
      <img
        src="exercise-images/site-images/muscle-map/13.C-Calves.png"
        className="muscle-image-calvesC"
        alt="CalvesC"
      />
      <img
        src="exercise-images/site-images/muscle-map/13.D-Calves.png"
        className="muscle-image-calvesD"
        alt="CalvesD"
      />
    </div>
  );

}

export default MuscleMap;